"""Lens 4: public metadata for every system in the frozen matrix.

Every field is either copied from a public page (URL in ``sources``) or marked
``None`` / "undisclosed". Dates are the date the SERVED snapshot became publicly
available (vendor announcement, arXiv v1, or OpenRouter catalogue ``created``
when that is the only dated source); ``date_basis`` says which. Nothing here was
measured by calling a model.

Fields
  vendor, family (for generation chains), release (YYYY-MM-DD), date_basis,
  open_weights, params_total_b / params_active_b (billions; None = undisclosed),
  arch: s2s-realtime | full-duplex-s2s | omni-speech-out | audio-in-llm | cascade
  speech_out: the model can emit speech itself (documented output modality)
  serving: file | realtime | local (how it ran here; PAPER Table 2 / §A.1)
"""

from __future__ import annotations

OR = "https://openrouter.ai/api/v1/models (created, description; fetched 2026-09-26)"
HF = "https://huggingface.co/api/models/{} (createdAt, safetensors total; fetched 2026-09-26)"

META: dict[str, dict] = {
    "gemini37or": dict(
        vendor="Google",
        family="gemini-flash-file",
        release="2026-08-13",
        date_basis="OpenRouter created",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR],
    ),
    "gemini38or": dict(
        vendor="Google",
        family="gemini-flash-file",
        release="2026-09-02",
        date_basis="OpenRouter created",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR],
    ),
    "gem25native": dict(
        vendor="Google",
        family="gemini-live",
        release="2025-12-12",
        date_basis="vendor blog (native-audio 12-2025 snapshot; -latest alias resolves to it)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=[
            "https://blog.google/products-and-platforms/products/gemini/gemini-audio-model-updates/",
            "https://discuss.ai.google.dev/t/gemini-2-5-flash-native-audio-still-on-12-2025-version-knowledge-cutoff-seems-outdated/134710",
        ],
    ),
    "geminilive": dict(
        vendor="Google",
        family="gemini-live",
        release="2026-03-26",
        date_basis="vendor blog",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=[
            "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-flash-live/"
        ],
    ),
    "gemini38live": dict(
        vendor="Google",
        family="gemini-live",
        release="2026-09-15",
        date_basis="vendor blog",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=[
            "https://blog.google/innovation-and-ai/technology/developers-tools/build-real-time-voice-applications-gemini-audio/",
            "https://www.marktechpost.com/2026/09/15/google-releases-gemini-3-8-live-and-3-8-live-extended-thinking-for-production-grade-voice-agents/",
        ],
    ),
    "gptaudio": dict(
        vendor="OpenAI",
        family="openai-audio",
        release="2026-01-19",
        date_basis="OpenRouter created (served 'new snapshot'; gpt-audio family GA 2025-08-28)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="omni-speech-out",
        speech_out=True,
        serving="file",
        sources=[OR],
    ),
    "gptaudiomini": dict(
        vendor="OpenAI",
        family="openai-audio",
        release="2026-01-19",
        date_basis="OpenRouter created (served snapshot)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="omni-speech-out",
        speech_out=True,
        serving="file",
        sources=[OR],
    ),
    "gptrt21": dict(
        vendor="OpenAI",
        family="openai-realtime",
        release="2026-07-06",
        date_basis="vendor announcement",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=[
            "https://community.openai.com/t/new-realtime-models-on-the-api-gpt-realtime-2-1-and-gpt-realtime-2-1-mini/1385896",
            "docs/MODEL-SCAN-2026-09.md §1.1",
        ],
    ),
    "gptrt21mini": dict(
        vendor="OpenAI",
        family="openai-realtime",
        release="2026-07-06",
        date_basis="vendor announcement",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=[
            "https://community.openai.com/t/new-realtime-models-on-the-api-gpt-realtime-2-1-and-gpt-realtime-2-1-mini/1385896"
        ],
    ),
    "grokvoice": dict(
        vendor="xAI",
        family="grok-voice",
        release="2026-07-29",
        date_basis="vendor announcement",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=["https://x.ai/news/grok-voice-think-fast-2"],
    ),
    "qwenrtflash": dict(
        vendor="Alibaba",
        family="qwen-omni",
        release="2026-03-30",
        date_basis="vendor blog (Qwen3.5-Omni; tech report 2604.15804)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=["https://qwen.ai/blog?id=qwen3.5-omni", "https://arxiv.org/abs/2604.15804"],
    ),
    "qwen38omni": dict(
        vendor="Alibaba",
        family="qwen-omni",
        release="2026-09-21",
        date_basis="OpenRouter created (tech report 2609.25611, v1 2026-09-22)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="omni-speech-out",
        speech_out=True,
        serving="file",
        sources=[OR, "https://arxiv.org/abs/2609.25611"],
    ),
    "qwen38rtflash": dict(
        vendor="Alibaba",
        family="qwen-omni",
        release="2026-09-22",
        date_basis="arXiv v1 (2609.25611)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=["https://arxiv.org/abs/2609.25611"],
    ),
    "qwenaudio31rt": dict(
        vendor="Alibaba",
        family="qwen-audio-rt",
        release="2026-09-21",
        date_basis="arXiv v1 (2609.25176)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="s2s-realtime",
        speech_out=True,
        serving="realtime",
        sources=["https://arxiv.org/abs/2609.25176"],
    ),
    "qwen3omni": dict(
        vendor="Alibaba",
        family="qwen-omni",
        release="2025-09-22",
        date_basis="vendor release (tech report 2509.17765; HF repo 2025-09-20)",
        open_weights=True,
        params_total_b=35.3,
        params_active_b=3.0,
        arch="omni-speech-out",
        speech_out=True,
        serving="local",
        sources=[HF.format("Qwen/Qwen3-Omni-30B-A3B-Instruct"), "https://arxiv.org/pdf/2509.17765"],
    ),
    "qwen25omni7b": dict(
        vendor="Alibaba",
        family="qwen-omni",
        release="2025-03-26",
        date_basis="vendor release (HF repo 2025-03-22)",
        open_weights=True,
        params_total_b=10.7,
        params_active_b=10.7,
        arch="omni-speech-out",
        speech_out=True,
        serving="local",
        sources=[HF.format("Qwen/Qwen2.5-Omni-7B")],
    ),
    "inkling": dict(
        vendor="Thinking Machines",
        family="inkling",
        release="2026-07-17",
        date_basis="OpenRouter created",
        open_weights=True,
        params_total_b=975.0,
        params_active_b=41.0,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR, HF.format("thinkingmachines/Inkling"), "docs/ROSTER-AUDIT-2026-08.md §4"],
    ),
    "musespark12": dict(
        vendor="Meta",
        family="muse-spark",
        release="2026-08-05",
        date_basis="OpenRouter created",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR],
    ),
    "mimo25": dict(
        vendor="Xiaomi",
        family="mimo",
        release="2026-04-22",
        date_basis="OpenRouter created (HF repo 2026-04-27)",
        open_weights=True,
        params_total_b=310.0,
        params_active_b=15.0,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR, HF.format("XiaomiMiMo/MiMo-V2.5"), "docs/ROSTER-AUDIT-2026-08.md §5"],
    ),
    "mimo26flash": dict(
        vendor="Xiaomi",
        family="mimo",
        release="2026-09-21",
        date_basis="OpenRouter created",
        open_weights=True,
        params_total_b=309.0,
        params_active_b=15.0,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR],
    ),
    "mimo26pro": dict(
        vendor="Xiaomi",
        family="mimo",
        release="2026-09-21",
        date_basis="OpenRouter created",
        open_weights=False,
        params_total_b=1000.0,
        params_active_b=None,  # "over 1T"; weights status UNVERIFIED
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR],
    ),
    "voxtral": dict(
        vendor="Mistral",
        family="voxtral",
        release="2025-07-15",
        date_basis="vendor release (HF repo 2025-07-01; OpenRouter 2025-10-30)",
        open_weights=True,
        params_total_b=24.3,
        params_active_b=24.3,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[HF.format("mistralai/Voxtral-Small-24B-2507"), OR],
    ),
    "nemotron": dict(
        vendor="NVIDIA",
        family="nemotron-omni",
        release="2026-04-28",
        date_basis="OpenRouter created (HF repo 2026-04-20)",
        open_weights=True,
        params_total_b=33.0,
        params_active_b=3.0,
        arch="audio-in-llm",
        speech_out=False,
        serving="file",
        sources=[OR, HF.format("nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16")],
    ),
    "stepaudio3": dict(
        vendor="StepFun",
        family="stepaudio",
        release="2026-09-12",
        date_basis="arXiv v1 (2609.14005)",
        open_weights=False,
        params_total_b=None,
        params_active_b=None,  # 196B/11B relayed, UNVERIFIED
        arch="omni-speech-out",
        speech_out=True,
        serving="file",
        sources=[
            "https://arxiv.org/abs/2609.14005",
            "docs/MODEL-SCAN-2026-09.md §2 (196B/11B relayed, unverified)",
        ],
    ),
    "gemma4e4b": dict(
        vendor="Google",
        family="gemma-4",
        release="2026-03-31",
        date_basis="vendor release per search summary (HF repo 2026-03-02)",
        open_weights=True,
        params_total_b=8.0,
        params_active_b=4.5,
        arch="audio-in-llm",
        speech_out=False,
        serving="local",
        sources=[HF.format("google/gemma-4-E4B-it"), "https://arxiv.org/html/2607.02770v1"],
    ),
    "gemma412b": dict(
        vendor="Google",
        family="gemma-4",
        release="2026-06-03",
        date_basis="vendor blog (HF repo 2026-05-23)",
        open_weights=True,
        params_total_b=12.0,
        params_active_b=12.0,
        arch="audio-in-llm",
        speech_out=False,
        serving="local",  # encoder-free multimodal
        sources=[
            HF.format("google/gemma-4-12B-it"),
            "https://blog.google/innovation-and-ai/technology/developers-tools/introducing-gemma-4-12b/",
        ],
    ),
    "phi4mm": dict(
        vendor="Microsoft",
        family="phi-4",
        release="2025-02-26",
        date_basis="vendor release (HF repo 2025-02-24)",
        open_weights=True,
        params_total_b=5.6,
        params_active_b=5.6,
        arch="audio-in-llm",
        speech_out=False,
        serving="local",
        sources=[HF.format("microsoft/Phi-4-multimodal-instruct")],
    ),
    "voicechat11b": dict(
        vendor="NVIDIA",
        family="nemotronlabs-voicechat",
        release="2026-07-29",
        date_basis="HF repo created (tech report 2609.21967 later)",
        open_weights=True,
        params_total_b=11.1,
        params_active_b=11.1,
        arch="full-duplex-s2s",
        speech_out=True,
        serving="local",
        sources=[
            HF.format("nvidia/NVIDIA-NemotronLabs-VoiceChat-11B"),
            "https://arxiv.org/abs/2609.21967",
        ],
    ),
    "ultravox8b": dict(
        vendor="Fixie",
        family="ultravox",
        release="2025-02-05",
        date_basis="HF repo created",
        open_weights=True,
        params_total_b=8.7,
        params_active_b=8.7,  # Llama-3.1-8B + 0.69B adapter
        arch="audio-in-llm",
        speech_out=False,
        serving="local",
        sources=[HF.format("fixie-ai/ultravox-v0_5-llama-3_1-8b")],
    ),
    "cascadeopen": dict(
        vendor="Groq (OpenAI weights)",
        family="cascade",
        release="2025-08-05",
        date_basis="gpt-oss-120b release",
        open_weights=True,
        params_total_b=117.0,
        params_active_b=5.1,
        arch="cascade",
        speech_out=False,
        serving="cascade",
        sources=["https://openai.com/index/introducing-gpt-oss/"],
    ),
}
